name: Nightly

on:
  push:
    paths:
      - "**.zig"
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: master
      - uses: actions/checkout@v3
      - run: zig fmt src/*.zig
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: master
      - uses: actions/checkout@v3
      - run: zig build test
  bench:
    runs-on: ubuntu-latest
    steps:
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: master
      - uses: actions/checkout@v3
      - run: zig build -Doptimize=ReleaseFast -Dcpu=baseline bench
